ROM node:16-alpine as build-step

RUN mkdir -p /app

WORKDIR /app

COPY emprende/package.json /app

RUN npm install

COPY emprende/ /app

# RUN /app/script.sh

RUN npm run build --prod

FROM nginx:1.17.1-alpine

COPY --from=build-step /app/dist/cart /usr/share/nginx/html

# Copy the NGINX configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 4200 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]