FROM nginx:1.17.1-alpine

COPY cart/ /usr/share/nginx/html

# Copy the NGINX configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 4200 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]